//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int ID { get; set; }
        public string Doctor { get; set; }
        public string Patient { get; set; }
        public string Time { get; set; }
        public string Room { get; set; }
    }
}
